apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: zookeeper-np-svc
  name: zookeeper-np-svc
  namespace: chat-system
spec:
  ports:
  - name: 2181-2181
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    app.kubernetes.io/instance: zookeeper
  type: NodePort
status:
  loadBalancer: {}
